### ISSUE TITLE
Rewrite of frontend

### ISSUE THREAD

**Issue by s-thom** [s-thom/the-index#43]
It's a bit annoying to work in there at the moment, it should be cleaned up

This issue may include doing #41 as well

---

### Tasks

- [x] Use React Router for client side routing
- [x] Rearrange router to better separate authorised from non-authorised routes
- [x] Change request logic
  - [x] `react-query`
  - [x] Maybe custom generator for `restful-react` type generation
- [x] styled components
- [x] New UI components for form controls
- [x] Smoother experience to enter tags
- [x] Better logged out experience
- [x] Proper tests for all UI components

**Comment by s-thom** [comment]
Part of this will involve redoing the unit tests, because they are bad.
